FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./SSL/cacert.pem /etc/nginx/ssl/cacert.pem
COPY ./SSL/servidor.key /etc/nginx/ssl/servidor.key
COPY ./SSL/servidor.crt /etc/nginx/ssl/servidor.crt

